TaskManager/ViewModels/DeleteViewModel.cs
namespace TaskManager.ViewModels;

/// <summary>
/// This model is used in the Delete View. It contains the Id used for deleting the item
/// </summary>
public class DeleteViewModel
{
	public int Id { get; set; }
}

TaskManager/ViewModels/TaskViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using TaskManager.ApplicationCore.Constants;
using TaskManager.Models;


namespace TaskManager.ViewModels;

/// <summary>
/// This model is used in the Edit and Create Views. It represents all the fields that should be filled and sent to the database
/// </summary>
public class TaskViewModel
{
	public int? Id { get; set; }
	[Required]
	[DisplayName("Task Message")]
	public string? TaskMessage { get; set; }
	[DisplayName("Date Chosen")]
	public DateTime DateChosen { get; set; } = DateTime.UtcNow;
	public bool Recurring { get; set; } = false;
	public string? CategoryId { get; set; }
	public List<CheckboxInput> Days { get; set; } = DaysOfWeek.Days().ConvertAll(e => new CheckboxInput { Text = e });
	[ValidateNever]
	public List<SelectListItem>? Categories { get; set; }
	public string DaysSelected { get; set; } = "";


	public void SetSelectedDays()
	{
		var days = DaysSelected.Split(',').ToList();
		if (!string.IsNullOrEmpty(DaysSelected) && DaysSelected.IndexOf(',') > 0)
		{
			Days = Days.Select((e, Index) =>
			{
				if (days.Contains(e.Text))
				{
					return new CheckboxInput() { IsChecked = true, Text = e.Text };
				}
				else
				{
					return new CheckboxInput() { IsChecked = false, Text = e.Text };
				}
			}).ToList();
		}

	}
}

TaskManager/Controllers/TaskController.cs
using AutoMapper;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaskManager.ApplicationCore.Extensions;
using TaskManager.ApplicationCore.Interfaces;
using TaskManager.ApplicationCore.Mediators.CreateTaskMediator;
using TaskManager.ApplicationCore.Mediators.DeleteTaskMediator;
using TaskManager.ApplicationCore.Mediators.GetTasksByUsernameMediator;
using TaskManager.ApplicationCore.Mediators.UpdateTaskMediator;
using TaskManager.Contracts.Requests;
using TaskManager.Models;
using TaskManager.ViewModels;

namespace TaskManager.Controllers;


[Authorize]
public class TaskController : Controller
{
	// GET: TaskController
	private readonly IMapper _mapper;
	private readonly ICategoryService _categoryService;
	private readonly IMediator _mediator;
	public TaskController(IMapper mapper, ICategoryService categoryService, IMediator mediator)
	{
		_mapper = mapper;
		_categoryService = categoryService;
		_mediator = mediator;
	}

	public async Task<IActionResult> Index()
	{
		var viewModel = new TaskByUsernameResponse();

		if (User.GetUserId() != null)
		{
			viewModel = await _mediator.Send(new TaskByUsernameRequest(User.GetUserId()));
		}

		return View(viewModel);

	}

	// GET: TaskController/Details/5
	public ActionResult Details(int id)
	{
		return View();
	}

	// GET: TaskController/Create
	public async Task<IActionResult> Create()
	{
		var vm = new TaskViewModel();
		vm.Categories = await GetAllCategories();

		return View(vm);
	}

	// POST: TaskController/Create

	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Create(TaskViewModel collection)
	{


		if (ModelState.IsValid)
		{
			CreateTaskRequest taskRequest = _mapper.Map<CreateTaskRequest>(collection);
			taskRequest.UserId = User.GetUserId();
			taskRequest.DaysSelected = GetDaysSelected(collection.Days);

			var response = await _mediator.Send(taskRequest);

			if (response.TaskCreated)
			{
				return RedirectToAction("Index", "Home");
			}
		}

		collection.Categories = await GetAllCategories();
		return View(collection);


	}

	// GET: TaskController/Edit/5


	public async Task<IActionResult> Edit(int id)
	{
		var response = await _mediator.Send(new TaskByIdRequest(id));
		if (response.TaskItem == null) return NotFound();

		TaskViewModel taskView = _mapper.Map<TaskViewModel>(response.TaskItem);
		taskView.SetSelectedDays();
		taskView.Categories = await GetAllCategories();
		return View(taskView);
	}

	// POST: TaskController/Edit/5
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Edit(TaskViewModel collection)
	{
		try
		{
			var updateTaskRequest = _mapper.Map<UpdateTaskRequest>(collection);
			updateTaskRequest.UserId = User.GetUserId();
			updateTaskRequest.DaysSelected = GetDaysSelected(collection.Days);
			var response = await _mediator.Send(updateTaskRequest);
			if (response.TaskUpdated)
			{
				return RedirectToAction("Index", "Home");
			}
			collection.Categories = await GetAllCategories();
			return View(collection);
		}
		catch
		{
			return View();
		}
	}

	public async Task<IActionResult> CheckTask(int id)
	{
		//Get Task
		if (id == null)
		{
			return RedirectToAction(nameof(Index));
		}
		var response = await _mediator.Send(new TaskByIdRequest(id));
		if (response.TaskItem == null) return NotFound();


		//Map Task Response to UpdateTask
		var updateTaskRequest = _mapper.Map<UpdateTaskRequest>(response.TaskItem);
		updateTaskRequest.UserId = User.GetUserId();
		updateTaskRequest.Completed = true;
		//Update Task
		var updateResponse = await _mediator.Send(updateTaskRequest);

		return RedirectToAction(nameof(Index));
	}

	// GET: TaskController/Delete/5
	public IActionResult Delete(int id)
	{
		return View(new DeleteViewModel() { Id = id });
	}

	// POST: TaskController/Delete/5
	[HttpPost]
	[ValidateAntiForgeryToken]
	[ActionName("Delete")]
	public async Task<IActionResult> DeleteItem(DeleteViewModel deleteView)
	{
		try
		{
			var response = await _mediator.Send(new DeleteTaskByIdRequest(deleteView.Id));
			if (response.TaskDeleted)
			{
				//alert sucessfully deleted
				return RedirectToAction(nameof(Index));
			}
			//alert: did not delete
			return RedirectToAction(nameof(Index));
		}
		catch
		{
			return View();
		}
	}



	private async Task<List<SelectListItem>> GetAllCategories()
	{
		var categories = await _categoryService.GetCategoriesAsync();
		return categories.ConvertAll(e => new SelectListItem()
		{
			Text = e.Name,
			Value = e.Id.ToString()

		});
	}

	private string GetDaysSelected(List<CheckboxInput> days)
	{
		var daysSelected = days.FindAll(e => e.IsChecked).Select(e => e.Text);
		return string.Join(",", daysSelected.ToArray());
	}
}

TaskManager/Views/Task/Create.cshtml
@model TaskViewModel;

<form method="post">
	<div class="m-1">
		<label asp-for="TaskMessage"></label>
		<input class="form-control" asp-for="TaskMessage" />
		<span asp-validation-for="TaskMessage"></span>
	</div>
	<div class="m-1">
		<label asp-for="DateChosen"></label>
		<input class="form-control" asp-for="DateChosen" />
		<span asp-validation-for="DateChosen"></span>
	</div>

	<div class="m-1">
		<label asp-for="Categories"></label>
		<select class="form-control" asp-items=@Model.Categories asp-for="CategoryId"></select>
		<span asp-validation-for="CategoryId"></span>
	</div>


	<div>
		<label>Select Days</label>
		<div class="d-flex flex-wrap">
			@for (var i = 0; i < Model.Days.Count; i++)
			{
				<div class="form-check mx-3">
					<input class="form-check-input" type="checkbox" asp-for="@Model.Days[i].IsChecked" />
					<label class="form-check-label">@(Model.Days[i].Text)</label>
					<input hidden asp-for="@Model.Days[i].Text" />
				</div>
			}

		</div>
	
	</div>
	<div>
		<div class="mt-3 form-check">
			<input class="form-check-input" type="checkbox"  asp-for="Recurring"  />
			<label class="form-check-label">Recurring</label>
		</div>
	</div>

	<button class="btn btn-primary" type="submit">Submit Form</button>

</form>

TaskManager/Views/Task/Delete.cshtml
@model DeleteViewModel;
<div>
	<form method="post">
		<div class="d-flex justify-content-center">

			<input hidden class="form-control" asp-for="Id"/>
			<div class="d-flex">
				<button type="submit" class="btn btn-danger m-2">Delete</button>
				<a class="btn btn-primary m-2" asp-action="Index" >Cancel</a>
			</div>
		</div>
	</form>
</div>

TaskManager/Views/Task/Edit.cshtml
@model TaskViewModel;

<form method="post">
	<input hidden asp-for="Id"/>
	<div class="m-1">
		<label asp-for="TaskMessage"></label>
		<input class="form-control" asp-for="TaskMessage" />
		<span asp-validation-for="TaskMessage"></span>
	</div>
	<div class="m-1">
		<label asp-for="DateChosen"></label>
		<input class="form-control" asp-for="DateChosen" />
		<span asp-validation-for="DateChosen"></span>
	</div>

	<div class="m-1">
		<label asp-for="Categories"></label>
		<select class="form-control" asp-items=@Model.Categories asp-for="CategoryId"></select>
		<span asp-validation-for="CategoryId"></span>
	</div>


	<div>
		<label>Select Days</label>
		<div class="d-flex flex-wrap">
			@for (var i = 0; i < Model.Days.Count; i++)
			{
				<div class="form-check mx-3">
					<input class="form-check-input" type="checkbox" asp-for="@Model.Days[i].IsChecked" />
					<label class="form-check-label">@(Model.Days[i].Text)</label>
					<input hidden asp-for="@Model.Days[i].Text" />
				</div>
			}

		</div>

	</div>
	<div>
		<div class="mt-3 form-check">
			<input class="form-check-input" type="checkbox" asp-for="Recurring" />
			<label class="form-check-label">Recurring</label>
		</div>
	</div>

	<button class="btn btn-primary" type="submit">Submit Form</button>

</form>

TaskManager/Views/Task/Index.cshtml
@model TaskByUsernameResponse


<div>
	<div class="d-flex justify-content-between">
		<div>
			<div class="d-flex align-items-center">
				<div class="HomePageFont">Tasks </div> <div>For the Day</div>
			</div>
			<div class="HomeBottomBar"></div>
		</div>
		<a asp-controller="Task" asp-action="Create">
			<button class="btn btn-primary">Add Task</button>
		</a>

	</div>

	<div style="overflow-x:auto;width:90vw">
		<table class="mt-2 table table-striped">
			<thead>
				<tr>
					<th style="width:400px">Task</th>
					<th>Category</th>
					<th>Completed</th>
					<th>Day</th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				@{
					foreach (var item in Model.Tasks)
					{

						<tr class="@(item.Completed? "text-white bg-dark":"")">
							
							<td>
								<a class="text-decoration-none" asp-action="CheckTask" asp-route-id=@(item.Id)>
								@item.TaskMessage
								</a>
							</td>
							<td>
								@item.Category?.Name
							</td>
							<td>
								@item.Completed
							</td>
							<td>
								@item.DaysSelected
							</td>
							<td>
								<div class="d-flex">
									<a asp-controller="Task" asp-action="Edit" asp-route-id="@(item.Id)">
										<button class="btn btn-primary">Edit</button>
									</a>

									<a asp-controller="Task" asp-action="Delete" asp-route-id="@(item.Id)">
										<button class="btn btn-danger">Delete</button>
									</a>



								</div>
							</td>
						
						</tr>

					}
				}

			</tbody>
		</table>
	</div>

</div>